server:
  port: 9093
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: light-framework-example
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 10s
#  jackson:
#    deserialization:
#      USE_BIG_DECIMAL_FOR_FLOATS: true
#    serialization:
#      WRITE_BIGDECIMAL_AS_PLAIN: true


